Add built-in topic to report the status of OpenDDS's internal threads
objectcomputing/OpenDDS pull request #1906
Opened 2020-09-28 22:02 UTC by jonesc-oci

2020-09-29 12:12 UTC, jwillemsen commented on dds/DCPS/Discovery.cpp
> +    DDS::ReturnCode_t ret = ts->register_type(participant,
``` suggestion
    const DDS::ReturnCode_t ret = ts->register_type(participant,
```

2020-09-29 12:14 UTC, jwillemsen commented on dds/DCPS/DiscoveryBase.h
> +        ACE_Time_Value expire = ACE_Time_Value(0);
Default constructor will initialise already to zero

2020-09-29 12:15 UTC, jwillemsen commented on dds/DCPS/DiscoveryBase.h
> +              ACE_Time_Value now = MonotonicTimePoint::now().value();
``` suggestion
             const ACE_Time_Value now = MonotonicTimePoint::now().value();
```

2020-09-29 12:15 UTC, jwillemsen commented on dds/DCPS/DiscoveryBase.h
> +                  status->lock.acquire_write();
Use a guard instead of manual acquire/release?

2020-09-29 12:17 UTC, jwillemsen commented on dds/DCPS/DiscoveryBase.h
> +      bool has_timeout;
Why have a seperate bool as member that indicates interval>0, use inline helper method? When you keep it, interval and has_timeout could be const when you initialise them directly

2020-09-29 12:18 UTC, jwillemsen commented on dds/DCPS/DiscoveryBase.h
> +      return dynamic_cast<InternalThreadBuiltinTopicDataDataReaderImpl*>(d.in());
This looks risky, the _var will decrement the refcount when it goes out of scope, you are using the pointer after that.

2020-09-29 12:19 UTC, jwillemsen commented on dds/DCPS/RTPS/Spdp.cpp
> +                ACE_TEXT("Status interval = %u.\n"), interval.value().sec()));
Why only log sec?

2020-09-29 12:21 UTC, jwillemsen commented on dds/DCPS/RTPS/Spdp.cpp
> +      thread_status_->lock.acquire_read();
guard?

2020-09-29 12:21 UTC, jwillemsen commented on dds/DCPS/ReactorTask.h
> +  ACE_Recursive_Thread_Mutex lock;
Needs this to be recursive?

2020-09-29 16:37 UTC, iguessthislldo requested changes

2020-09-29 16:37 UTC, iguessthislldo commented on dds/DCPS/BuiltInTopicUtils.h
> +enum { NUMBER_OF_BUILT_IN_TOPICS = 7 };
```suggestion
const size_t NUMBER_OF_BUILT_IN_TOPICS = 7;
```

2020-09-29 16:37 UTC, iguessthislldo commented on dds/DCPS/Discovery.cpp
> +  if (CORBA::is_nil(bit_internal_thread_topic)) {
```suggestion
  if (!bit_internal_thread_topic) {
```

2020-09-29 16:37 UTC, iguessthislldo commented on tests/DCPS/InternalThreadStatus/InternalThreadStatusListenerImpl.h
> +                                            DDS::DataReader_ptr reader,
```suggestion
  virtual void on_requested_deadline_missed(DDS::DataReader_ptr reader,
```

2020-09-29 16:37 UTC, iguessthislldo commented on dds/DCPS/ReactorTask.h
> +  OPENDDS_MAP(unsigned long, ACE_Time_Value) map;
Please avoid dealing with `ACE_Time_Value`s unless you're dealing directly with ACE.

2020-10-01 03:22 UTC, iguessthislldo commented on dds/DCPS/transport/framework/QueueTaskBase_T.h
> +  /// name for trhead monitoring BIT
```suggestion
  /// name for thread monitoring BIT
```

2020-10-06 22:15 UTC, jrw972 requested changes

2020-10-06 22:15 UTC, jrw972 commented on dds/DCPS/RTPS/Spdp.cpp
> +void Spdp::SpdpTransport::thread_status_task(const DCPS::MonotonicTimePoint& /*now*/)
What challenges are there to moving the reporting logic into the Service Participant or at least the DomainParticipantImpl?  That way, it generalizes to all types of discovery.  Alternatively, we could forego the thread status map and have each thing that would be inserting into the map just write its instance when necessary.

I'm not interested is doing this right now but I would like to know if there are certain challenges to doing so.

2020-10-07 21:58 UTC, mitza-oci requested changes

2020-10-07 21:58 UTC, mitza-oci commented on dds/DCPS/DiscoveryBase.h
> +                  }
```suggestion
                  ACE_WRITE_GUARD_RETURN(ACE_Thread_Mutex, g, status->lock, -1);
                  status->map[key] = now;
```

2020-10-07 21:58 UTC, mitza-oci commented on dds/DCPS/DiscoveryBase.h
> +            do {
Can these be combined?

2020-10-07 21:58 UTC, mitza-oci commented on dds/DCPS/DiscoveryBase.h
> +              MonotonicTimePoint now = MonotonicTimePoint::now();
```suggestion
              const MonotonicTimePoint now = MonotonicTimePoint::now();
```

2020-10-07 21:58 UTC, mitza-oci commented on dds/DCPS/RTPS/Spdp.cpp
> +      {
```suggestion
```

2020-10-07 21:58 UTC, mitza-oci commented on dds/DCPS/transport/framework/TransportImpl.cpp
> +TransportImpl::create_reactor_task(bool useAsyncSend, const OPENDDS_STRING name)
```suggestion
TransportImpl::create_reactor_task(bool useAsyncSend, const OPENDDS_STRING& name)
```

2020-10-07 21:58 UTC, mitza-oci commented on dds/DCPS/DiscoveryBase.h
> +      inline bool has_timeout() {
```suggestion
      bool has_timeout() const {
```
already inline (defined within class definition)

2020-10-16 16:02 UTC, mitza-oci requested changes

2020-10-23 20:16 UTC, mitza-oci approved these changes

2020-10-24 19:36 UTC, merged