Statistic Update for RtpsRelay
objectcomputing/OpenDDS pull request #1930
Opened 2020-10-06 18:53 UTC by jrw972

* Adds a topic for Participants
* Adds a separate topic for Participant Statistics
* Removes "monitor mode"
* All statistics are written p.r.n.

2020-10-07 20:26 UTC, brattonj-oci commented
OK, looks fine though it looks like you changed port numbers. Any specific reason?

2020-10-07 20:27 UTC, brattonj-oci approved these changes

2020-10-07 23:59 UTC, mitza-oci requested changes

2020-10-07 23:59 UTC, mitza-oci commented on tools/rtpsrelay/Config.h
> +  void statistics_interval(const OpenDDS::DCPS::TimeDuration& flag)
Is there a name other than `flag` we could use here?

2020-10-07 23:59 UTC, mitza-oci commented on tools/rtpsrelay/DomainStatisticsReporter.h
> +                           DomainStatisticsDataWriter_ptr writer)
Could this use `_var`?

2020-10-07 23:59 UTC, mitza-oci commented on tools/rtpsrelay/DomainStatisticsReporter.h
> +    domain_statistics_.total_readers(0);
seems redundant

2020-10-07 23:59 UTC, mitza-oci commented on tools/rtpsrelay/ParticipantListener.h
> +  explicit ParticipantListener(OpenDDS::DCPS::DomainParticipantImpl* participant,
```suggestion
  ParticipantListener(OpenDDS::DCPS::DomainParticipantImpl* participant,
```

2020-10-07 23:59 UTC, mitza-oci commented on tools/rtpsrelay/ParticipantListener.h
> +                               ParticipantEntryDataWriter_ptr participant_writer);
smart pointers preferred for both of these

2020-10-07 23:59 UTC, mitza-oci commented on tools/rtpsrelay/ParticipantStatisticsReporter.h
> +    participant_statistics_._max_fan_out = std::max(participant_statistics_._max_fan_out, static_cast<uint32_t>(value));
```suggestion
    participant_statistics_.max_fan_out() = std::max(participant_statistics_.max_fan_out(), static_cast<uint32_t>(value));
```

2020-10-08 02:28 UTC, jrw972 commented
> OK, looks fine though it looks like you changed port numbers. Any specific reason?

I found out that the IANA has those ports set aside for RTPS traffic.  https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?skey=8&page=102

2020-10-08 13:41 UTC, mitza-oci approved these changes

2020-10-08 13:42 UTC, merged