BIT topics are spec-defined memory leak
objectcomputing/OpenDDS pull request #1940
Opened 2020-10-10 02:47 UTC by jrw972

Problem
-------

The DDS Specification says that the members of the
ReaderDataLifecycleQosPolicy are set to infinite which means a
participant will never purge the data stored in the builtin topics.  A
long-running participant will eventually run out of memory.

It is possible to manually change the qos for all of the builtin
participant data readers.  However, the addition of a new builtin
topic would render such code useless and the new builtin topic would
create another memory leak.

Solution
--------

Provide a mechanism to configure the ReaderDataLifecycleQosPolicy for
the builtin topic data readers.

2020-10-10 14:42 UTC, jrw972 commented
As an alternative, we could provide a function that sets the durations on all of the readers.

2020-10-12 13:46 UTC, mitza-oci commented
Spec issue DDS15-46 https://issues.omg.org/issues/lists/dds-rtf5#issue-14097

2020-10-12 13:48 UTC, mitza-oci requested changes

2020-10-12 13:48 UTC, mitza-oci commented on dds/DCPS/Service_Participant.cpp
> +    bit_autopurge_disposed_samples_delay_({DDS::DURATION_INFINITE_SEC, DDS::DURATION_INFINITE_NSEC})
This will fail on older compilers

2020-10-12 13:48 UTC, mitza-oci commented on tools/rtpsrelay/RtpsRelay.cpp
> +  const DDS::Duration_t one_minute = { 0, 0 };
```suggestion
  const DDS::Duration_t one_minute = { 60, 0 };
```

2020-10-12 15:29 UTC, jrw972 commented on tools/rtpsrelay/RtpsRelay.cpp
> +  const DDS::Duration_t one_minute = { 0, 0 };
Oops.

2020-10-13 15:41 UTC, mitza-oci approved these changes

2020-10-14 12:55 UTC, merged