RtpsRelay Improvements
objectcomputing/OpenDDS pull request #1970
Opened 2020-10-26 00:55 UTC by jrw972

* Remove governor
* Remove output queuing
* Add processing time statistic
* Add dropped messages statistic
* Add new address statistic
* Add expired address statistic
* Add claim count statistic
* Add disclaim count statistic
* Add Relay Statistics
* Normalize and reformat log messages
* Domain statistics printed on change

2020-10-26 18:23 UTC, iguessthislldo approved these changes

2020-10-27 02:18 UTC, mitza-oci requested changes

2020-10-27 02:18 UTC, mitza-oci commented on tools/rtpsrelay/RtpsRelay.cpp
> +  auto relay_statistics_writer_var = relay_publisher->create_datawriter(relay_statistics_topic, writer_qos, nullptr, OpenDDS::DCPS::DEFAULT_STATUS_MASK);
Use a _var type

2020-10-27 02:18 UTC, mitza-oci commented on tools/rtpsrelay/RtpsRelay.cpp
> +  const auto t = participant_statistics_writer->get_topic();
Use a _var type

2020-10-27 14:23 UTC, mitza-oci approved these changes

2020-10-28 04:15 UTC, merged