SPDP lease processing is not scalable
objectcomputing/OpenDDS pull request #1999
Opened 2020-11-02 19:43 UTC by jrw972

Problem
-------

Every time the SPDP transport sends a local announcement, it loops
over all discovered participants to check if they have expired.  This
is not scalable.  Furthermore, participants with long resend periods
may accumulate a number of long expired participants.

Solution
--------

Use a TimeQueue and sporadic task to process the lease expirations as needed.

2020-11-02 21:59 UTC, mitza-oci requested changes

2020-11-02 21:59 UTC, mitza-oci commented on dds/DCPS/RTPS/Spdp.h
> +  typedef std::multimap<DCPS::MonotonicTimePoint, DCPS::RepoId> TimeQueue;
Use allocators

2020-11-02 21:59 UTC, mitza-oci commented on dds/DCPS/RTPS/Spdp.cpp
> +  // Remove previous expiration.
Merge with similar code from `remove_discovered_participant_i`?

2020-11-03 16:45 UTC, mitza-oci commented on dds/DCPS/RTPS/Spdp.cpp
>    ACE_UNUSED_ARG(iter);
```suggestion
```

2020-11-03 22:32 UTC, mitza-oci approved these changes

2020-11-03 23:44 UTC, simpsont-oci approved these changes

2020-11-03 23:44 UTC, simpsont-oci commented on dds/DCPS/RTPS/Spdp.cpp
> +  remove_lease_expiration_i(iter);
Does this need to recalculate the scheduled wait? Or is it sufficient to just let it wake up, decide that nothing happens and then reschedule?

2020-11-03 23:44 UTC, simpsont-oci commented on dds/DCPS/RTPS/Spdp.h
> +  TimeQueue lease_expirations_;
This TimeQueue thing seems like it could pretty easily be its own utility class with its own logic and unit test. Just sayin'.

2020-11-03 23:44 UTC, simpsont-oci commented on dds/DCPS/RTPS/Spdp.h
> +  TimeQueue handshake_resends_;
Especially if we're going to reuse it 3 times!

2020-11-03 23:44 UTC, simpsont-oci commented on dds/DCPS/RTPS/Spdp.cpp
> +    tport_->lease_expiration_processor_->schedule(lease_expirations_.begin()->first - now);
Is now correct enough by this point in the function to use in calculating a relative wait period to the next expiration? We might want to update "now" as part of the loop or at least here at the end before the calculation. Carefully though, so we're not trying to schedule a negative relative wait time.

2020-11-04 12:41 UTC, merged