When we have C++11 use std::atomic instead of ACE_Atomic
objectcomputing/OpenDDS pull request #2050
Opened 2020-11-13 10:50 UTC by jwillemsen

2020-11-13 17:12 UTC, iguessthislldo commented on dds/DCPS/DataBlockLockPool.h
> +#endif
https://github.com/objectcomputing/OpenDDS/blob/master/docs/guidelines.md#preprocessor

2020-11-16 23:15 UTC, mitza-oci commented on dds/DCPS/DataReaderImpl.cpp
> +  if (entity_deleted_ == true) {
```suggestion
  if (get_deleted()) {
```

2020-11-17 08:04 UTC, iguessthislldo requested changes

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/RTPS/Spdp.h
> +# include "ace/Atomic_Op.h"
```suggestion
#  include <atomic>
#else
#  include <ace/Atomic_Op.h>
```

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/RTPS/Spdp.h
> +  bool shutting_down() {
```suggestion
  bool shutting_down()
  {
```

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/RcObject.h
> +# include "ace/Atomic_Op.h"
```suggestion
#  include <atomic>
#else
#  include <ace/Atomic_Op.h>
```

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/ReceivedDataElementList.h
> +# include "ace/Atomic_Op_T.h"
```suggestion
#  include <atomic>
#else
#  include <ace/Atomic_Op_T.h>
```

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/TopicDescriptionImpl.h
> +# include "ace/Atomic_Op.h"
```suggestion
#  include <atomic>
#else
#  include <ace/Atomic_Op.h>
```

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/WaitSet.h
> +# include "ace/Atomic_Op.h"
```suggestion
#  include <atomic>
#else
#  include <ace/Atomic_Op.h>
```

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/WriterInfo.h
> +# include "ace/Atomic_Op.h"
```suggestion

#ifdef ACE_HAS_CPP11
#  include <atomic>
#else
#  include <ace/Atomic_Op.h>
```

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/transport/framework/TransportQueueElement.h
> +#endif
```suggestion
#ifdef ACE_HAS_CPP11
#  include <atomic>
#else
#  include <ace/Atomic_Op.h>
#endif
```

Also this should go after the dds includes.

2020-11-17 08:04 UTC, iguessthislldo commented on dds/DCPS/transport/tcp/TcpDataLink.h
> +# include "ace/Atomic_Op.h"
```suggestion
#  include <atomic>
#else
#  include <ace/Atomic_Op.h>
```

2021-01-04 17:05 UTC, iguessthislldo approved these changes

2021-01-04 22:27 UTC, merged