Wrap and Deprecate ACE_Condition
objectcomputing/OpenDDS pull request #2114
Opened 2020-11-30 18:27 UTC by iguessthislldo

Prompted by https://github.com/objectcomputing/OpenDDS/pull/2106. Do a similar thing to `ACE_Condition` as what was done to `ACE_Time_Value` in https://github.com/objectcomputing/OpenDDS/pull/1256, which is to wrap and deprecate it. In wrapping it we can force monotonic time behavior and make it so it only accepts `MonotonicTimePoint` and `TimeDuration`.

Fixed include order along the way, including a pretty bad case in the `RecorderImpl` files where the header depended on the include order in the source file.

2020-11-30 18:35 UTC, jwillemsen commented on dds/DCPS/Condition.h
> +    ACE_ERROR((LM_ERROR, "(%P|%t) ERROR: Condition::wait: %p\n"));
Logging based on log level?

2020-12-04 23:04 UTC, mitza-oci requested changes

2020-12-04 23:04 UTC, mitza-oci commented on tests/DCPS/Deadline/DataWriterListenerImpl.h
> +  mutable  matched_condition_;
What type is this supposed to have?

2020-12-05 00:01 UTC, iguessthislldo commented on dds/DCPS/MessageTracker.cpp
> +      loop = false;
It should keep trying even if it got an error?

2020-12-05 00:06 UTC, mitza-oci commented
No, the line after it is a "return" so this is a dead store

On Fri, Dec 4, 2020, 6:01 PM Fred Hornsey <notifications@github.com> wrote:

> *@iguessthislldo* commented on this pull request.
> ------------------------------
>
> In dds/DCPS/MessageTracker.cpp
> <https://github.com/objectcomputing/OpenDDS/pull/2114#discussion_r536452630>
> :
>
> >        break;
> +
> +    case CvStatus_NoTimeout:
> +      break;
> +
> +    case CvStatus_Error:
> +    default:
> +      if (DCPS_debug_level) {
> +        ACE_ERROR((LM_ERROR, "(%P|%t) ERROR: MessageTracker::wait_messages_pending: "
> +          "error in wait_until\n"));
> +      }
> +      loop = false;
>
> It should keep trying even if it got an error?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/objectcomputing/OpenDDS/pull/2114#discussion_r536452630>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACM4T2SOETAETD2MOH7G7ILSTFZ5ZANCNFSM4UH57X7Q>
> .
>

2020-12-05 02:09 UTC, mitza-oci approved these changes

2020-12-05 15:47 UTC, merged