Patch for Android API30 Reconnect.
objectcomputing/OpenDDS pull request #2250
Opened 2021-01-06 22:07 UTC by ClaytonCalabrese

The previous PR was failing windows java builds.  This should resolve that issue.

2021-01-06 22:22 UTC, iguessthislldo requested changes

2021-01-06 22:22 UTC, iguessthislldo commented on java/dds/dcps_java.mpc
> +    android_jar_file = $(if $(ANDROID_ABI),-classpath $(android_sdk)/platforms/android-$(android_target_api)/android.jar)
```suggestion
    android_target_api ?= 0
    need_network_callback = $(shell [ $(android_target_api) -ge 24 ] && echo "ok")
    opendds_android_network_callback = $(if $(need_network_callback),AndroidNetworkCallback.java,FakeAndroidNetworkCallback.java)
    android_jar_file = $(if $(need_network_callback),-classpath $(android_sdk)/platforms/android-$(android_target_api)/android.jar)
```

This reduces the line length and avoids passing `-classpath` if we don't need to.

2021-01-07 18:42 UTC, iguessthislldo commented
[Doing another matrix run](https://github.com/iguessthislldo/OpenDDS-Android/actions/runs/469654580) even though I don't expect there to any issues. After we address the issue on mealworm I would say this is done.

2021-01-07 21:00 UTC, mitza-oci approved these changes

2021-01-07 22:06 UTC, merged

2021-01-07 22:06 UTC, iguessthislldo approved these changes