Type consistency enforcement Qos
objectcomputing/OpenDDS pull request #2364
Opened 2021-01-29 03:06 UTC by sonndinh

2021-02-01 16:22 UTC, kuznetsovmoci requested changes
Do we need code in Sedp.cpp, ParameterListConverter.cpp, etc. to support new QoS type_consistency parameter?

2021-02-01 17:08 UTC, sonndinh commented
> Do we need code in Sedp.cpp, ParameterListConverter.cpp, etc. to support new QoS type_consistency parameter?

I'm not sure about `Sedp`, but probably `ParameterListConverter` will need to be updated.

2021-02-05 21:56 UTC, mitza-oci requested changes

2021-02-05 21:56 UTC, mitza-oci commented on bin/dcps_tests.lst
> +tests/DCPS/XTypes/run_test.pl --type-consistency: !DCPS_MIN
Does it need to have the `--type-consistency` command line argument if that's the only way it's ever invoked?

2021-02-05 21:56 UTC, mitza-oci commented on dds/DCPS/RTPS/Sedp.cpp
> +  const CORBA::ULong added_len = sub.remote_expectant_opendds_associations_.size();
See warnings reported by GitHub Actions on this line

2021-02-05 21:56 UTC, mitza-oci commented on dds/DCPS/XTypes/TypeAssignability.h
> +  explicit TypeAssignability(TypeLookupService_rch tls,
```suggestion
  TypeAssignability(TypeLookupService_rch tls,
```

2021-02-05 21:56 UTC, mitza-oci commented on tests/DCPS/XTypes/Pub/XTypesPublisher.cpp
> +  ReturnCode_t ret = pdw->write(pcs, HANDLE_NIL);
```suggestion
  const ReturnCode_t ret = pdw->write(pcs, HANDLE_NIL);
```

2021-02-05 21:56 UTC, mitza-oci commented on tests/DCPS/XTypes/Pub/XTypesPublisher.cpp
> +    ACE_ERROR((LM_ERROR, "ERROR: create_participant failed"));
```suggestion
    ACE_ERROR((LM_ERROR, "ERROR: create_participant failed\n"));
```

2021-02-07 17:57 UTC, mitza-oci approved these changes

2021-02-08 03:59 UTC, merged