idl reduction/splitting of TryConstruct due to issue #2368
objectcomputing/OpenDDS pull request #2370
Opened 2021-01-29 20:53 UTC by ClaytonCalabrese

IDL was generating files too large causing memory errors on build machines. This PR should fix that issue by splitting the idl into 3 different files.  Each of these files is less than half the size of the previous combined generated TSImpl file.

2021-01-29 21:10 UTC, mitza-oci commented
If there is duplication across IDL files, why not use `#include`?

2021-01-29 21:20 UTC, ClaytonCalabrese commented
> If there is duplication across IDL files, why not use `#include`?

I'm not sure how exactly the memory management works with these idl files, and so without a way to directly test it, I was trying to play it safe by avoiding #includes.

Do #includes not stay in memory when building idl?

2021-01-29 21:22 UTC, mitza-oci commented
> 
> 
> > If there is duplication across IDL files, why not use `#include`?
> 
> I'm not sure how exactly the memory management works with these idl files, and so without a way to directly test it, I was trying to play it safe by avoiding #includes.
> 
> Do #includes not stay in memory when building idl?

The goal is to reduce the size of each individual TypeSupportImpl.cpp.  Not to reduce the size of the preprocessed IDL.

2021-01-29 22:16 UTC, iguessthislldo requested changes

2021-01-29 22:16 UTC, iguessthislldo commented on tests/DCPS/Compiler/xcdr/xcdr2.idl
> +};
Missing EOF newline

2021-01-30 03:56 UTC, sonndinh reviewed
Can the IDL files be split and named so that it's easier to tell what's inside each resulting file?

2021-01-30 03:56 UTC, sonndinh commented on tests/DCPS/Compiler/TryConstruct/TryConstructBaseTypes.idl
> +//due to issue 1900, enums in C++11 need an extra value beyond each case when used as a union discriminator
```suggestion
// enum for use in struct, union, and sequence
// due to issue 1900, enums in C++11 need an extra value beyond each case when used as a union discriminator
```
Similar comment for the remaining lines of this file (and other files).

2021-01-30 03:56 UTC, sonndinh commented on tests/DCPS/Compiler/TryConstruct/TryConstructBaseTypes.idl
> +
```suggestion
```

2021-01-30 03:56 UTC, sonndinh commented on tests/DCPS/Compiler/TryConstruct/TryConstruct2.idl
> +  };
```suggestion
  @mutable
  struct DiscardStructString1 {
    str64 str64_d;
  };
```

2021-01-30 03:56 UTC, sonndinh commented on tests/DCPS/Compiler/TryConstruct/TryConstruct3.idl
> +  };
```suggestion
  @mutable
  struct NestedStructTest1 {
    NestedStruct2 ns;
  };

  @mutable
  struct NestedStructTest2 {
    @try_construct(USE_DEFAULT) NestedStruct3 ns;
  };
```

2021-02-01 22:45 UTC, iguessthislldo requested changes
Could you rename `mutabletypes.idl` to `mutable_types.idl`?

2021-02-02 02:43 UTC, sonndinh commented on tests/DCPS/Compiler/TryConstruct/AnonTypes.idl
> +    sequence <EnumType, 3> AnonEnumSeqBound;
```suggestion
    sequence<EnumType, 3> AnonEnumSeqBound;
```
For other sequences too.

2021-02-02 02:43 UTC, sonndinh commented on tests/DCPS/Compiler/TryConstruct/AnonTypes.idl
> +    @try_construct(USE_DEFAULT) sequence < EnumType, 2> AnonEnumSeqBound;
```suggestion
    @try_construct(USE_DEFAULT) sequence <EnumType, 2> AnonEnumSeqBound;
```

2021-02-02 02:43 UTC, sonndinh commented on tests/DCPS/Compiler/TryConstruct/AnonTypes.idl
> +    str20ArrayTrim AnonArrayArr [3];
```suggestion
    str20ArrayTrim AnonArrayArr[3];
```

2021-02-02 17:11 UTC, sonndinh approved these changes

2021-02-02 17:32 UTC, iguessthislldo approved these changes

2021-02-04 14:02 UTC, merged