Idl reduction xcdr test
objectcomputing/OpenDDS pull request #2418
Opened 2021-02-12 20:31 UTC by ClaytonCalabrese

XCDR test was still timing out on remedy fedora so it requires addition splitting of its idl.

In the process of doing this I found a bug in the TS generation and fixed it.

2021-02-12 20:47 UTC, iguessthislldo requested changes

2021-02-12 20:47 UTC, iguessthislldo commented on tests/DCPS/Compiler/xcdr/appendable_mixed.idl
> +#include <xcdrbasetypes.idl>
```suggestion
#include "xcdrbasetypes.idl"
```

Also should go above TAO includes.

2021-02-12 20:47 UTC, iguessthislldo commented on tests/DCPS/Compiler/xcdr/mutable_types2.idl
> +#include <xcdrbasetypes.idl>
```suggestion
#include "mutable_types.idl"
#include "xcdrbasetypes.idl"

#include <tao/LongSeq.pidl>
#include <tao/ShortSeq.pidl>
#include <tao/OctetSeq.pidl>
#include <tao/StringSeq.pidl>
```

2021-02-12 20:47 UTC, iguessthislldo commented on tests/DCPS/Compiler/xcdr/keyonly.idl
> +#include <xcdrbasetypes.idl>
```suggestion
#include "xcdrbasetypes.idl"
```

Also should go above TAO includes.

2021-02-12 21:18 UTC, iguessthislldo approved these changes

2021-02-15 16:26 UTC, ClaytonCalabrese commented
Looks like some stuff is broken due to the fix. I'll look into them.

2021-02-16 14:18 UTC, merged