Misc. Logging Changes
objectcomputing/OpenDDS pull request #2467
Opened 2021-03-05 07:06 UTC by iguessthislldo

- Log when Readers and Writers get a GUID. Also logs the topic type and topic name.
- Fix missing dash before metadata in OpenDDS version logging.
- Make all thread status logging I could find start at 4 to match the update logging point.
- Slap `DCPS_debug_level` on some logging points that were missing them.

2021-03-05 17:07 UTC, mitza-oci approved these changes

2021-03-05 17:44 UTC, mitza-oci commented
Are the errors detected in `tests/security/attributes` (GHPRB) new from this PR?

2021-03-05 17:50 UTC, iguessthislldo commented
I think they're expected to fail, but I changed it from a warning to an error to match the other error returns that log in that function.

2021-03-05 17:51 UTC, iguessthislldo commented
I will look into more and fix it.

2021-03-09 00:15 UTC, mitza-oci requested changes

2021-03-09 00:15 UTC, mitza-oci commented on dds/DCPS/DataWriterImpl.cpp
> +      topic_servant_->get_name(), topic_servant_->get_type_name()));
Use `_var` or the methods that don't start with `get_*` from `TopicImpl.h`

2021-03-09 00:39 UTC, mitza-oci approved these changes

2021-03-09 14:12 UTC, merged