Slow and no longer existing readers slow association
objectcomputing/OpenDDS pull request #2472
Opened 2021-03-07 22:44 UTC by jrw972

Problem
-------

A slow or no longer existing reader will cause the heartbeat period to
grow to the maximum.  This will persist until the defunct reader is
purged from the sytem.

Solution
--------

1. Remove the logic for computing an adaptive heartbeat period.

2. Use a separate timer for nack responses.

3. Add filtering based on reflecting heartbeat counts that discards
   acknacks that are too old.  This is to handle cases where the
   round-trip latency is greater than the heartbeat period.

2021-03-08 17:34 UTC, iguessthislldo requested changes

2021-03-08 17:34 UTC, iguessthislldo commented on dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
> +RtpsUdpDataLink::RtpsWriter::gather_nack_replies_i(MetaSubmessageVec& meta_submessages)
Please update function name in the logging.

2021-03-08 17:34 UTC, iguessthislldo commented on tests/DCPS/SetQosPartition/Writer.cpp
> +                    ACE_TEXT ("wait_for_acknowledgments returned %d.\n"),
```suggestion
                    ACE_TEXT("wait_for_acknowledgments returned %d.\n"),
```

Or put a space in the other one if we're sticking with the old style, I don't know, it just bothers me that they're different.

2021-03-08 17:34 UTC, iguessthislldo commented on dds/DCPS/transport/rtps_udp/RtpsUdpDataLink.cpp
> +RtpsUdpDataLink::RtpsWriter::send_nack_responses(const DCPS::MonotonicTimePoint& /*now*/)
```suggestion
RtpsUdpDataLink::RtpsWriter::send_nack_responses(const MonotonicTimePoint& /*now*/)
```

Pretty sure this is the `DCPS` namespace.

2021-03-08 18:34 UTC, iguessthislldo approved these changes

2021-03-11 14:17 UTC, mitza-oci commented
Parsing the testing logs on GHPRB failed.  The actual test failures were:
- tests/DCPS/Thrasher/run_test.pl high rtps
- tests/DCPS/Thrasher/run_test.pl aggressive rtps
- tests/DCPS/Thrasher/run_test.pl high rtps durable
- tests/DCPS/Thrasher/run_test.pl aggressive rtps durable
- performance-tests/bench/run_test.pl disco show-logs

2021-03-11 23:17 UTC, jrw972 commented
retest this please

2021-03-22 21:29 UTC, merged