Github Actions: Safety Profile
objectcomputing/OpenDDS pull request #2493
Opened 2021-03-16 16:32 UTC by ClaytonCalabrese

This PR adds the safety builds to github actions

2021-03-16 19:56 UTC, simpsont-oci commented on .github/workflows/build_and_test.yml
> +        $GITHUB_WORKSPACE/autobuild/autobuild.pl "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/config.xml"
These all seem to be missing the "upload artifact" & "check results" steps of the other test jobs, so we won't know if they fail (unless it's a build failure).

2021-03-16 21:56 UTC, simpsont-oci commented on .github/workflows/build_and_test.yml
> +        $GITHUB_WORKSPACE/autobuild/autobuild.pl "$GITHUB_WORKSPACE/OpenDDS/build/target/${{ github.job }}_autobuild_workspace/config.xml"
Also, now that the wait_cancel_previous PR is merged, these should all get a "needs: wait_cancel_previous".

2021-03-16 21:57 UTC, simpsont-oci requested changes
See general comments. We need to check / display the autobuild test results, and these should add a "needs: wait_cancel_previous" to help with workflow queuing / cancelation.

2021-03-17 20:12 UTC, simpsont-oci commented
The build_u18_gcc8_i0_js0_j looks like it's failing because it's running out of disk space when building bench. This is odd though, since --no-rapidjson should (and normally does) prevent bench from getting built. Can you try to figure out why it's not honoring --no-rapidjson? That alone might solve the build size issue...

2021-03-17 21:00 UTC, ClaytonCalabrese commented
> The build_u18_gcc8_i0_js0_j looks like it's failing because it's running out of disk space when building bench. This is odd though, since --no-rapidjson should (and normally does) prevent bench from getting built. Can you try to figure out why it's not honoring --no-rapidjson? That alone might solve the build size issue...

I'm assuming it is because the ACE_TAO isn't built with it.  I'll change that and see what happens.

2021-03-22 19:17 UTC, ClaytonCalabrese commented
Unfortunately the deletion of the commented parts of the safety builds has confused the hell out of git and so the changes look pretty sloppy.  Not sure why it is having so much trouble with that.

2021-03-25 21:26 UTC, simpsont-oci commented
Since the diffs are screwy I'm going to make general comments here:
- Still a lot of test failures that are "Can't spawn X" or "X doesn't exist" so we don't have the test flags quite right yet.
- Pretty sure you don't want the XERCES test flag for either safety profile build. I'm hoping that's causing most of the trouble.
- Even though they're not used anywhere at the moment, I would add the "SAFETY_BASE" and "SAFETY_EXTENDED" flags to their respective builds. It should make it easier to selectively disable tests if those flags are already set for auto_run_tests.

2021-03-30 14:59 UTC, simpsont-oci approved these changes

2021-03-30 16:43 UTC, merged