Update article-intro.html
objectcomputing/OpenDDS pull request #2500
Opened 2021-03-18 08:13 UTC by jwillemsen

* Use annotations
* Use register_instance instead of _cxx_register
* Removed old throw specifications

2021-03-18 08:13 UTC, jwillemsen commented
Fixed #2455

2021-03-18 22:03 UTC, mitza-oci requested changes

2021-03-18 22:03 UTC, mitza-oci commented on about/articles/Article-Intro.html
> +<code>@key</code> annocaton defined for each type is a unique identifier for each
```suggestion
<code>@key</code> annotation defined for each type is a unique identifier for each
```

2021-03-18 22:19 UTC, jwillemsen commented on about/articles/Article-Intro.html
> +<code>@key</code> annocaton defined for each type is a unique identifier for each
Thanks!

2021-03-19 14:36 UTC, mitza-oci approved these changes

2021-03-19 14:36 UTC, merged