Cleanup Reactor Task
objectcomputing/OpenDDS pull request #2548
Opened 2021-04-05 18:33 UTC by simpsont-oci

Problem:
On reuse of ReactorTask, any existing reactors and/or proactors are potentially leaked.

Solution:
Don't do that.

2021-04-05 18:53 UTC, iguessthislldo requested changes

2021-04-05 18:53 UTC, iguessthislldo commented on dds/DCPS/ReactorTask.cpp
> +ReactorTask::cleanup()
```suggestion
void ReactorTask::cleanup()
```

Rest of the file uses the one line signature style.

2021-04-05 18:53 UTC, iguessthislldo commented on dds/DCPS/ReactorTask.cpp
>    }
It's bothered me for awhile that the else blocks are the same here. Maybe something like this?

```c++
#if defined (ACE_WIN32) && defined (ACE_HAS_WIN32_OVERLAPPED_IO)
  if (use_async_send_ && !reactor_) {
    reactor_ = new ACE_Reactor(new ACE_WFMO_Reactor, 1);

    ACE_WIN32_Proactor* proactor_impl = new ACE_WIN32_Proactor(0, 1);
    proactor_ = new ACE_Proactor(proactor_impl, 1);
    reactor_->register_handler(proactor_impl, proactor_impl->get_handle());
  } else
#endif
  if (!reactor_) {
    reactor_ = new ACE_Reactor(new ACE_Select_Reactor, true);
    proactor_ = 0;
  }
```

2021-04-05 20:25 UTC, mitza-oci commented
Could we add the execute bit check to lint for `*.pl`?

2021-04-05 20:54 UTC, iguessthislldo commented
> Could we add the execute bit check to lint for *.pl?

Yes. I have though about this before, but for the opposite case, where there's a file that has the execute bit that shouldn't.

2021-04-06 15:28 UTC, iguessthislldo approved these changes

2021-04-06 21:59 UTC, merged