ManualAsserLiveliness test is brittle
objectcomputing/OpenDDS pull request #2568
Opened 2021-04-08 19:49 UTC by jrw972

Problem
-------

The ManualAssertLiveliness test fails when the timing changes.

Solution
--------

* Coorindate startup by ensuring that the readers and writers are associated.

* Coordinate shutdown by checking that the reader has received the
  appropriate number of messages and the appropriate number of callbacks.

2021-04-08 19:49 UTC, jrw972 commented
I would like this to an exemplar test so please help me remove as much cruft as possible.

2021-04-08 22:00 UTC, mitza-oci requested changes

2021-04-09 16:42 UTC, mitza-oci commented on tests/Utils/DistributedConditionSet.h
> +typedef OpenDDS::DCPS::RcHandle<DistributedConditionSet> DistributedConditionSetHandle;
Something related to this change seems to have broken the build

2021-04-09 16:42 UTC, mitza-oci commented on tests/Utils/DistributedConditionSet.h
> +  void post(const std::string& actor, const std::string& condition) {
Looks like there are more of these, for example `InMemoryDistributedConditionSet::wait_for`.

2021-04-30 18:18 UTC, mitza-oci approved these changes

2021-05-03 15:07 UTC, merged