Rtps relay improvements
objectcomputing/OpenDDS pull request #2578
Opened 2021-04-13 03:49 UTC by jrw972

2021-04-13 04:04 UTC, mitza-oci requested changes

2021-04-13 04:04 UTC, mitza-oci commented on tools/rtpsrelay/RtpsRelay.cpp
> +  }
Should this error result in `EXIT_FAILURE`?

2021-04-13 21:52 UTC, mitza-oci approved these changes

2021-04-14 02:20 UTC, iguessthislldo approved these changes

2021-04-14 14:34 UTC, merged