Github Actions: Add ace7tao3 build to GHA
objectcomputing/OpenDDS pull request #2600
Opened 2021-04-22 16:16 UTC by ClaytonCalabrese

Someday we want to be on ace7tao3 and we want a GHA build to check on our compatibility over time. This PR adds that to the u20_j_qt_ws_sec build.  There are multiple options for ACE7TAO3: major, minor, and micro.  I settled on minor but am open to changing.

2021-04-22 16:36 UTC, jwillemsen commented
I think micro would be the best option, a minor release is each 1.5 to 2 years, major took us 10 years ;-)

2021-04-22 16:39 UTC, mitza-oci requested changes

2021-04-22 16:39 UTC, mitza-oci commented on .github/workflows/build_and_test.yml
> +        ref: Latest_ACE7TAO3_Minor
This should track master, same concept as ace6tao2.

2021-04-22 19:27 UTC, mitza-oci requested changes

2021-04-22 19:27 UTC, mitza-oci commented on .github/workflows/build_and_test.yml
> +        ref: master
```suggestion
```

I assume it just uses the default branch?

2021-04-23 15:56 UTC, iguessthislldo approved these changes

2021-04-23 15:58 UTC, mitza-oci approved these changes

2021-04-23 16:25 UTC, merged