XTypes: Integrate complete  TypeObject with builtin topics
objectcomputing/OpenDDS pull request #2772
Opened 2021-06-26 02:58 UTC by sonndinh

2021-07-19 17:01 UTC, ClaytonCalabrese requested changes
There are a bunch of test failures in the CI. I'd recommend merging from master and then trying to figure out what is causing the failures.

Seems like a bunch of compiler tests as well as the XTypes test are experiencing problems.

2021-07-19 18:00 UTC, sonndinh commented on dds/DCPS/DiscoveryBase.h
> +        // endpoint's TypeInformation, then the "complete" part also is not included.
I talked to Adam about this but I think we haven't had a conclusive answer. Our matching process is assuming the `minimal` member is always present in `TypeInformation` but the spec seems not exclude the case when only the `complete` member is present. We probably need a further discussion on this.

2021-07-19 18:03 UTC, sonndinh commented on dds/DCPS/RTPS/Sedp.cpp
> +    }
I think it's kind of small to put into a function.

2021-07-19 18:05 UTC, sonndinh commented on dds/DCPS/Service_Participant.cpp
> +  return XTypes::TypeObject();
Fixed

2021-07-24 03:33 UTC, closed without merging

2021-07-24 03:38 UTC, sonndinh commented
GitHub shows incorrect commit history for this PR after I merged master to the xtypes_dynamic branch, and the xtypes_dynamic branch to the PR's branch. So I opened PR #2876 to replace this PR. The new PR shows the correct commit history.