typeobject hash consistency fix
objectcomputing/OpenDDS pull request #2804
Opened 2021-07-05 02:11 UTC by pmesnier

see jira ticket 352. The problem was that the type objects for complete and minimal sequences and arrays had a field that was left uninitialized by the default constructor. so when those objects were serialized, hashed, then written out in a type support impl file, the hash would vary from one run to the next.

This patch solves theproblemby explicitly initializing the otherwise unused collection flag value.

2021-07-07 04:22 UTC, sonndinh commented on dds/DCPS/XTypes/TypeObject.h
> +    , element()
```suggestion
    CompleteSequenceType()
      : collection_flag(0)
      , header()
      , element()
```

2021-07-07 04:22 UTC, sonndinh commented on dds/DCPS/XTypes/TypeObject.h
> +    , element()
```suggestion
    MinimalSequenceType()
      : collection_flag(0)
      , header()
      , element()
```

2021-07-07 04:22 UTC, sonndinh commented on dds/DCPS/XTypes/TypeObject.h
> +      MinimalSequenceType(CollectionTypeFlag a_collection_flag,
```suggestion
    MinimalSequenceType(CollectionTypeFlag a_collection_flag,
```

2021-07-07 04:22 UTC, sonndinh commented on dds/DCPS/XTypes/TypeObject.h
> +    , element()
```suggestion
    CompleteArrayType()
      : collection_flag(0)
      , header()
      , element()
```

2021-07-07 04:22 UTC, sonndinh commented on dds/DCPS/XTypes/TypeObject.h
> +    , element()
```suggestion
    MinimalArrayType()
      : collection_flag(0)
      , header()
      , element()
```

2021-07-07 08:29 UTC, iguessthislldo commented on tests/DCPS/Compiler/typeobject_hash_consistency/run_test.pl
> +my $gencmd = "$ENV{DDS_ROOT}/bin/opendds_idl -Sa -St --no-dcps-data-type-warnings sample.idl";
```suggestion
my $gencmd = "$ENV{DDS_ROOT}/bin/opendds_idl -Sa -St sample.idl";
```

2021-07-08 01:36 UTC, sonndinh approved these changes

2021-07-08 03:24 UTC, iguessthislldo requested changes

2021-07-08 03:24 UTC, iguessthislldo commented on tests/DCPS/Compiler/typeobject_hash_consistency/run_test.pl
> +my $result = system("diff pass1 sampleTypeSupportImpl.cpp");
Also I don't think `diff` is portable

2021-07-09 13:37 UTC, mitza-oci requested changes

2021-07-09 13:37 UTC, mitza-oci commented on tests/DCPS/Compiler/typeobject_hash_consistency/run_test.pl
> +system("mv sampleTypeSupportImpl.cpp pass1");
Don't assume that the system has a `mv` command.  Renaming can be handled by the perl script without spawning an external process.

2021-07-09 17:12 UTC, iguessthislldo requested changes

2021-07-09 17:12 UTC, iguessthislldo commented on tests/DCPS/Compiler/typeobject_hash_consistency/run_test.pl
> +system($gencmd);
Need to check the return of `system`.

2021-07-09 17:12 UTC, iguessthislldo commented on tests/DCPS/Compiler/typeobject_hash_consistency/run_test.pl
> +rename("sampleTypeSupportImpl.cpp","pass1");
```suggestion
rename("sampleTypeSupportImpl.cpp", "pass1");
```

2021-07-09 17:12 UTC, iguessthislldo commented on tests/DCPS/Compiler/typeobject_hash_consistency/run_test.pl
> +my $result = compare("pass1","sampleTypeSupportImpl.cpp");
```suggestion
my $result = compare("pass1", "sampleTypeSupportImpl.cpp");
```

2021-07-09 20:11 UTC, iguessthislldo approved these changes

2021-07-09 23:59 UTC, merged