Update NEWS File for 3.18
objectcomputing/OpenDDS pull request #2883
Opened 2021-07-29 05:19 UTC by iguessthislldo

2021-08-02 20:07 UTC, mitza-oci commented on NEWS.md
> +  - Fixed `TypeObject` hash being inconsistent (#2804)
This is more general than RTPS.  We could combine it with #2749.

2021-08-03 21:15 UTC, mitza-oci requested changes

2021-08-03 21:15 UTC, mitza-oci commented on NEWS.md
> +  - `docs/internal/docs.rst`: describes how to build and extend the documentation ($2767)
```suggestion
  - `docs/internal/docs.rst`: describes how to build and extend the documentation (#2767)
```

2021-08-04 04:34 UTC, iguessthislldo commented on NEWS.md
> +  - `docs/internal/docs.rst`: describes how to build and extend the documentation ($2767)
Ah, well it's getting removed anyways.

2021-08-04 11:58 UTC, simpsont-oci approved these changes

2021-08-04 15:13 UTC, mitza-oci approved these changes

2021-08-24 15:32 UTC, merged