GitHub Actions: Update .lst flags
objectcomputing/OpenDDS pull request #2953
Opened 2021-08-27 18:54 UTC by ClaytonCalabrese

The goal of this PR is to document why we have some tests blocked from running in GitHub Actions, and to unblock things that are failing also on the scoreboard.

I removed the flags and after each run, if a test failed on both the latest scoreboard run, as well as the CI run, I reblocked it and logged the reason for test failure.

Here is my google sheets I used for logging failures: 

https://docs.google.com/spreadsheets/d/1S9UfzzA_2PF9pWW3znLuYKvi2OlA04QG-qwYxDfCJ3k/edit?usp=sharing

If you feel there are any of the tests listed in the spreadsheet that should also be blocked, please let me know.

Additionally, if you feel any of the blocked tests should be unblocked, please let me know.

2021-08-30 14:55 UTC, simpsont-oci commented
I would ignore the bench stuff... there's already a draft PR I've been tracking for bench that does the same thing but with other config tweaks / etc.

2021-09-03 15:41 UTC, mitza-oci approved these changes

2021-09-03 18:42 UTC, simpsont-oci approved these changes

2021-09-08 18:42 UTC, iguessthislldo requested changes

2021-09-08 18:42 UTC, iguessthislldo commented on docs/internal/github_actions.rst
> +GitHub Actions runners.
Can you make this and the rest of the rst changes [one line per sentence](https://opendds.readthedocs.io/en/latest/internal/docs.html#rst-sphinx-usage)?

2021-09-09 16:50 UTC, iguessthislldo approved these changes

2021-09-10 03:43 UTC, merged