Add test case for when we want to use a sequence of a topic type in a…
objectcomputing/OpenDDS pull request #2966
Opened 2021-09-03 07:32 UTC by jwillemsen

…nother IDL type

    * tests/DCPS/Compiler/idl_test3_lib/FooDef.idl:

2021-09-03 07:32 UTC, jwillemsen commented
Reproducer for #2965

2021-09-03 08:36 UTC, jwillemsen commented
Fixed #2965

2021-09-03 15:22 UTC, iguessthislldo requested changes

2021-09-03 15:22 UTC, iguessthislldo commented on dds/idl/be_global.cpp
> +  static const char TYPESEQUENCESUFFIC_FLAG[] = "--typeSequenceSuffix=";
```suggestion
  static const char TYPESEQUENCESUFFIC_FLAG[] = "--type-sequence-suffix=";
```

To match the other long options.

2021-09-04 07:51 UTC, jwillemsen commented on dds/idl/be_global.cpp
> +  static const char TYPESEQUENCESUFFIC_FLAG[] = "--typeSequenceSuffix=";
Changed

2021-09-07 20:53 UTC, iguessthislldo requested changes

2021-09-07 20:53 UTC, iguessthislldo commented on dds/idl/be_global.cpp
> +  static const char TYPESEQUENCESUFFIC_FLAG[] = "--type-sequence-suffix=";
```suggestion
  static const char TYPESEQUENCESUFFIX_FLAG[] = "--type-sequence-suffix=";
```

Change the other uses of this.

Also add `--type-sequence-suffix` to [`--help`](https://github.com/objectcomputing/OpenDDS/blob/28ce33c4ff01963861abce7a3f77c0ef865c8117/dds/idl/be_util.cpp#L99).

2021-09-08 15:26 UTC, iguessthislldo approved these changes

2021-09-10 19:08 UTC, mitza-oci requested changes

2021-09-10 19:08 UTC, mitza-oci commented on dds/idl/be_util.cpp
> +    ACE_TEXT(" --type-sequence-suffix=<postfix>\tset the implied DDS sequence postfix (default is 'Seq')\n")
```suggestion
    ACE_TEXT(" --type-sequence-suffix=<postfix>\tset the implied DDS sequence suffix (default is 'Seq')\n")
```

2021-09-10 19:55 UTC, mitza-oci commented
An equivalent option (but under a different name) used to be supported, starting with a011cf5ee7a923a8d11a05f945d25894420eecaf and ending at 9b87c5f4785204369f1280fda66ae84aabd8fcba

Based on this, I wonder if the same name should be used here.  It also follows the pattern of using `-Wb,` for fine tuning and little-used options (like `-X` for the JVM).

2021-09-10 20:39 UTC, jwillemsen commented
I am fine with using the option used in the past, will update this PR next week

2021-09-13 06:47 UTC, jwillemsen commented
Updated PR to use `-Wb,opendds_sequence_suffix`

2021-09-13 22:02 UTC, mitza-oci requested changes
The generated files need to be in `.gitignore`.  Other than that I think it's ready.
https://github.com/objectcomputing/OpenDDS/pull/2966/checks?check_run_id=3583850340

2021-09-14 20:15 UTC, mitza-oci approved these changes

2021-09-15 18:19 UTC, merged