RTPS Discovery max_lease_duration config option
objectcomputing/OpenDDS pull request #2999
Opened 2021-09-13 23:58 UTC by ClaytonCalabrese

This PR creates a max_lease_duration option that limits what participants can set their lease duration to be.

I set the default at 2x the default lease duration (600 seconds).

2021-09-14 19:08 UTC, jrw972 requested changes

2021-09-14 19:08 UTC, jrw972 commented on dds/DCPS/RTPS/Spdp.cpp
> +    if (pdata.leaseDuration.seconds > maxLeaseDuration) {
```suggestion
    if (maxLeaseDuration && pdata.leaseDuration.seconds > maxLeaseDuration) {
```

2021-09-14 19:08 UTC, jrw972 commented on dds/DCPS/RTPS/Spdp.cpp
> +    if (pdata.leaseDuration.seconds > maxLeaseDuration) {
This gives people a way to opt-out by setting it to 0.

2021-09-15 15:38 UTC, ClaytonCalabrese commented
**test_m10_o1d0_sec**

tests/DCPS/PersistentInfoRepo/run_test.pl
tests/DCPS/XTypes/run_test.pl
tests/security/attributes/run_test.pl SC0_sec_sub
tests/security/attributes/run_test.pl FullMsgEncrypt_SubMsgSign

**test_u20_p1_asan_sec**
tests/DCPS/EntityLifecycleStress/run_test.pl publishers 5 subscribers 5

Seem new. I'll look into the test failures as well as I can because I do not have access to a mac.

2021-09-16 22:50 UTC, ClaytonCalabrese commented
Okay I think those tests might have just been a coincidence?

They haven't shown up again in the last 2 runs.

2021-09-17 18:20 UTC, jrw972 requested changes

2021-09-17 18:20 UTC, jrw972 commented on dds/DCPS/RTPS/Spdp.cpp
> +    ::CORBA::Long maxLeaseDuration = config_->max_lease_duration().to_dds_duration().sec;
This block should be conditional on !from_sedp (which would be a secure update).

2021-09-17 22:22 UTC, jrw972 approved these changes

2021-09-18 13:13 UTC, merged