Changed RawDataSample to include the header so that we can deserialize a XCDR2 stream
objectcomputing/OpenDDS pull request #3028
Opened 2021-09-24 07:19 UTC by jwillemsen

At the moment `rtps_udp` is used as transport the data is encoded using XCDR2 which we can only deserialize when we have some more information available as part of the `RawDataSample`. Instead of adding even more fields we now pass the `DataSampleHeader` with all available information. 

Added a new unit test do demonstrate how to deserialize the `RawDataSample` in user code, in the near future we can hopefully use DynamicData from DDSXTypes for this.

Fixed #3025.

2021-09-24 22:49 UTC, iguessthislldo requested changes

2021-09-28 13:36 UTC, mitza-oci commented
In the current design (in master), RawDataSample provides isolation from the internal DataSampleHeader.  It seems like the only field needed for the test which is not already in RawDataSample is cdr_encapsulation_.

2021-09-28 13:41 UTC, jwillemsen commented
> In the current design (in master), RawDataSample provides isolation from the internal DataSampleHeader. It seems like the only field needed for the test which is not already in RawDataSample is cdr_encapsulation_.

I am not 100% certain that we have enough fields for all user code, instead of adding field by field I decided to expose the DataSampleHeader completely giving the Recorder access to all possible data.

2021-09-28 13:44 UTC, jwillemsen commented
And when DDSTypes Dynamic is ready on master I would assume we migrate to that, but this way we only have 1 change to get any user code working before that is ready.

2021-10-01 20:57 UTC, mitza-oci approved these changes

2021-10-03 14:48 UTC, merged