OpenSSL 3.0 compatibility
objectcomputing/OpenDDS pull request #3139
Opened 2021-11-05 02:33 UTC by pmesnier

2021-11-10 14:51 UTC, mitza-oci requested changes

2021-11-10 14:51 UTC, mitza-oci commented on dds/DCPS/security/OpenSSL_legacy.h
> +#elseif OPENSSL_VERSION_NUMBER <   0x30000000L
```suggestion
#elif OPENSSL_VERSION_NUMBER < 0x30000000L
```

2021-11-11 22:09 UTC, mitza-oci commented
I'm not sure what happened with this PR, but GitHub is listing it as "pmesnier wants to merge 89 commits into master from plm-jira-393".  It may be easier to start a new branch with just the commit needed for OpenSSL 3.

2021-11-15 18:29 UTC, pmesnier commented
This PR is superseded by PR 3164

2021-11-15 18:29 UTC, closed without merging