OpenSSL 3.0 compatibility
objectcomputing/OpenDDS pull request #3164
Opened 2021-11-15 18:27 UTC by pmesnier

Replaces PR 3139, due to peculiar rebase result.

2021-11-15 21:29 UTC, mitza-oci requested changes

2021-11-15 21:29 UTC, mitza-oci commented on dds/DCPS/security/OpenSSL_legacy.h
> +#elseif OPENSSL_VERSION_NUMBER <   0x30000000L
Same comment I had on the other PR

2021-11-16 15:52 UTC, mitza-oci approved these changes

2021-11-16 15:59 UTC, mitza-oci commented
Since we know 3.0.0 doesn't work, how about checking for 3.0.1 or higher and having it error out if 3.0.0 is used?

2021-11-16 19:04 UTC, iguessthislldo requested changes

2021-11-16 19:04 UTC, iguessthislldo commented on dds/DCPS/security/OpenSSL_legacy.h
> +#elif OPENSSL_VERSION_NUMBER <   0x30000000L
```suggestion
#elif OPENSSL_VERSION_NUMBER < 0x30000000L
```

2021-11-18 21:46 UTC, iguessthislldo approved these changes

2021-11-19 04:57 UTC, merged