XTypes Dynamic: Fix dt_map_ race
objectcomputing/OpenDDS pull request #3199
Opened 2021-12-02 17:31 UTC by ClaytonCalabrese

There was a race between the populating of the dt_map_ and the checking of the map.

2021-12-02 17:42 UTC, jrw972 requested changes

2021-12-02 17:42 UTC, jrw972 commented on dds/DCPS/RecorderImpl.cpp
> +RecorderImpl::add_to_dt_map(PublicationId pub_id, const XTypes::TypeIdentifier& ti)
```suggestion
RecorderImpl::add_to_dynamic_type_map(PublicationId pub_id, const XTypes::TypeIdentifier& ti)
```

2021-12-02 17:42 UTC, jrw972 commented on dds/DCPS/RecorderImpl.h
> +  void add_to_dt_map(PublicationId pub_id, const XTypes::TypeIdentifier& ti);
```suggestion
  void add_to_dynamic_type_map(PublicationId pub_id, const XTypes::TypeIdentifier& ti);
```

2021-12-02 17:42 UTC, jrw972 commented on dds/DCPS/RTPS/Sedp.cpp
> +            ri->add_to_dt_map(rac.writer_id(), type_info.complete.typeid_with_size.type_id);
I'm assuming that this not a "complete" solution.

2021-12-02 19:16 UTC, jrw972 approved these changes

2021-12-03 20:51 UTC, mitza-oci requested changes

2021-12-03 20:51 UTC, mitza-oci commented on dds/DCPS/RecorderImpl.cpp
> +RecorderImpl::add_to_dynamic_type_map(PublicationId pub_id, const XTypes::TypeIdentifier& ti)
```suggestion
RecorderImpl::add_to_dynamic_type_map(const PublicationId& pub_id, const XTypes::TypeIdentifier& ti)
```

2021-12-03 20:51 UTC, mitza-oci commented on dds/DCPS/RecorderImpl.h
> +  void add_to_dynamic_type_map(PublicationId pub_id, const XTypes::TypeIdentifier& ti);
```suggestion
  void add_to_dynamic_type_map(const PublicationId& pub_id, const XTypes::TypeIdentifier& ti);
```

2021-12-03 20:52 UTC, mitza-oci approved these changes

2021-12-03 20:54 UTC, merged