Add WaitForAck Tests To TSAN
objectcomputing/OpenDDS pull request #3253
Opened 2021-12-23 07:18 UTC by simpsont-oci

2022-01-06 15:40 UTC, jrw972 requested changes
I think that most of my "capture references to repo ids" should be ignored.

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +  PublicationId info_writer_id = info.writer_id();
```suggestion
  const PublicationId& info_writer_id = info.writer_id();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +    WriterInfo::WriterState info_state = info.state();
```suggestion
    const WriterInfo::WriterState& info_state = info.state();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +  PublicationId info_writer_id = info.writer_id();
```suggestion
  const PublicationId& info_writer_id = info.writer_id();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +  WriterInfo::WriterState info_state = info.state();
```suggestion
  const WriterInfo::WriterState& info_state = info.state();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +  PublicationId info_writer_id = info.writer_id();
```suggestion
  const PublicationId& info_writer_id = info.writer_id();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +  WriterInfo::WriterState info_state = info.state();
```suggestion
  const WriterInfo::WriterState& info_state = info.state();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +  PublicationId writer_id = writer->writer_id();
```suggestion
  const PublicationId& writer_id = writer->writer_id();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataReaderImpl.cpp
> +  RepoId publisher_id = writer->publisher_id();
```suggestion
  const RepoId& publisher_id = writer->publisher_id();
```

2022-01-06 15:40 UTC, jrw972 commented on dds/DCPS/DataWriterImpl.cpp
> +      GuidConverter writer_converter(this->publication_id_);
Use LogGuid.

2022-01-06 17:52 UTC, mitza-oci commented on dds/DCPS/WriterInfo.h
>    };
```suggestion
  WriterState state() const
  {
    ACE_Guard<ACE_Thread_Mutex> guard(mutex_);
    return state_;
  }
```
more like this

2022-01-06 17:52 UTC, mitza-oci commented on dds/DCPS/transport/framework/TransportClient.h
> +  virtual const RepoId get_repo_id() const = 0;
```suggestion
  virtual RepoId get_repo_id() const = 0;
```

2022-01-10 14:24 UTC, mitza-oci approved these changes

2022-01-10 23:59 UTC, merged