Extend DpShutdown Test, PerlDDS Improvements
objectcomputing/OpenDDS pull request #3270
Opened 2022-01-14 22:51 UTC by iguessthislldo

- DpShutdown Test
  - Extend to cover shutdown and delete related stuff added in https://github.com/objectcomputing/OpenDDS/pull/3159
  - Reformat to bring in line with the style guidelines
  - Cleanup `run_test.pl`
- PerlDDS
  - Remove unused `value_flag` and `get_value_flag`, add ability to get flag value using an optional argument to `flag`.
  - Add support for `DCPSLogLevel`
  - Put `-ORBLogFile` first to make sure debug level set and other messages are in the log file.
- Fix typos in log messages

2022-01-14 23:01 UTC, mitza-oci requested changes

2022-01-14 23:01 UTC, mitza-oci commented on tests/DCPS/DpShutdown/dpshutdown.cpp
> +    DDS::DataWriter_var dw = pub->create_datawriter(topic1.in(),
```suggestion
    DDS::DataWriter_var dw = pub->create_datawriter(topic1,
```

If we're going to "re-style" I'd suggest taking out `.in()` everywhere it's not needed, making `_nil()` just `0` and not use `DEFAULT_STATUS_MASK` when there's no listener.

Certainly not required though.

2022-01-14 23:45 UTC, iguessthislldo commented on bin/PerlDDS/Run_Test.pm
> +    $params = "-ORBLogFile $file_name.log $params"
Why doesn't this cause a syntax error?

2022-01-15 16:43 UTC, mitza-oci commented on bin/PerlDDS/Run_Test.pm
> +    $params = "-ORBLogFile $file_name.log $params"
https://perldoc.perl.org/perlsyn#Simple-Statements

2022-01-15 16:47 UTC, mitza-oci approved these changes
Are the errors in tests/DCPS/MultiTopic/run_test.pl due to changes in bin/PerlDDS/Run_Test.pm?

2022-01-18 14:08 UTC, merged