MultiTopic Test Fix
objectcomputing/OpenDDS pull request #3277
Opened 2022-01-20 06:58 UTC by ClaytonCalabrese

The MultiTopic test is experiencing a few failures on the OpenDDS Scoreboard. Among these is one where an improperly joined sample in being inserted using `store_synthetic_data`. This happens if the order of received topics is done in such a way that all keys are known, but not all topics are received. A a topic causing cross join would then need to be received before the other remaining topic, leading to the failure.

Currently still need to resolve how to deal with the `ACE_GUARD` because it is attempting an empty `return` if uncommented.

2022-01-20 07:37 UTC, iguessthislldo commented
> Currently still need to resolve how to deal with the ACE_GUARD because it is attempting an empty return if uncommented.

`ACE_GUARD_RETURN` is the form of `ACE_GUARD` with a return value if the mutex lock attempt fails. There is a `ACE_READ_GUARD_RETURN` as well, but I think @mitza-oci has commented before that the read/write specific mutexes don't apply to any platform we use. As a side note, for a mutex failure for `DDS::ReturnCode_t` I personally use `DDS::RETCODE_OUT_OF_RESOURCES`, but I'm not sure it matters too much and a `DDS::RETCODE_ERROR` would probably be okay too.

2022-01-20 14:28 UTC, mitza-oci commented
> > Currently still need to resolve how to deal with the ACE_GUARD because it is attempting an empty return if uncommented.
> 
> `ACE_GUARD_RETURN` is the form of `ACE_GUARD` with a return value if the mutex lock attempt fails. 

Yes, you can use this macro (see `Global_Macros.h`), or you can use the ACE objects directly without macros.

>There is a `ACE_READ_GUARD_RETURN` as well, but I think @mitza-oci has commented before that the read/write specific mutexes don't apply to any platform we use. As a side note, for a mutex failure for `DDS::ReturnCode_t` I personally use `DDS::RETCODE_OUT_OF_RESOURCES`, but I'm not sure it matters too much and a `DDS::RETCODE_ERROR` would probably be okay too.

Readers/writer locks are a whole different design dimension.  If you're not already using them I'd go with just simple mutexes.  RW locks are an optimization of that, which can be handled separately. I don't think I said that they don't apply -- I think all platforms do support them in some way.  But there is overhead to managing the more complex synchronization object so it's not going to be faster in all cases.  Probably depends on how many concurrent readers would be expected.

2022-01-20 20:36 UTC, iguessthislldo requested changes

2022-01-20 20:36 UTC, iguessthislldo commented on dds/DCPS/MultiTopicDataReader_T.cpp
> +        DDS::ReturnCode_t ret = join(resulting, *i, no_keys, NULL, qp.data_reader_, other_meta);
```suggestion
        const DDS::ReturnCode_t ret = join(resulting, *i, no_keys, 0, qp.data_reader_, other_meta);
```

And the rest of the return codes.

2022-01-20 20:36 UTC, iguessthislldo commented on dds/DCPS/MultiTopicDataReader_T.cpp
> +          DDS::ReturnCode_t ret = join(join_result, starting[i], keys,
```suggestion
          const DDS::ReturnCode_t ret = join(join_result, starting[i], keys,
```

2022-01-20 20:36 UTC, iguessthislldo commented on dds/DCPS/MultiTopicDataReader_T.h
>                       SampleVec starting, const TopicSet& seen,
Can you fix the indent here and below?

2022-01-24 20:59 UTC, iguessthislldo approved these changes

2022-01-24 23:05 UTC, merged