Release message block chains after each get_*_value(s) call in DynamicData
objectcomputing/OpenDDS pull request #3296
Opened 2022-01-25 20:33 UTC by sonndinh

2022-01-25 21:48 UTC, mitza-oci requested changes

2022-01-25 21:48 UTC, mitza-oci commented on dds/DCPS/XTypes/DynamicData.h
> +  const IntermediateChains& get_intermediate_chains() { return chains_to_release; }
Could these be private?

2022-01-25 21:48 UTC, mitza-oci commented on dds/DCPS/XTypes/DynamicData.h
> +  const IntermediateChains& get_intermediate_chains() { return chains_to_release; }
```suggestion
  typedef OPENDDS_VECTOR(ACE_Message_Block*) IntermediateChains;
  const IntermediateChains& get_intermediate_chains() const { return chains_to_release; }
```

2022-01-25 21:48 UTC, mitza-oci commented on dds/DCPS/XTypes/DynamicData.h
> +    ScopedChainManager(DynamicData& dd)
```suggestion
    explicit ScopedChainManager(DynamicData& dd)
```

2022-01-26 14:26 UTC, mitza-oci approved these changes
Does this use case work?  I think it does, but just want to verify.  If it's not already in tests we may want to add it.
```
DynamicData d2;
{
  DynamicData d1(init_for_overall_data_sample);
  d1.get_complex_value(d2, id_nested);
}
// d2 is still valid
```

2022-01-26 16:24 UTC, sonndinh commented
> 

Yes, it should work because `d2` is independent of `d1`. I'll add a test case for that.

2022-01-26 22:54 UTC, merged