OpenSSL 3 integration to avoid deprecated function calls. *incomplete*
objectcomputing/OpenDDS pull request #3358
Opened 2022-02-24 14:00 UTC by pmesnier

still working on DH and EC secret sharing functions.

2022-03-03 01:50 UTC, ClaytonCalabrese requested changes

2022-03-03 01:50 UTC, ClaytonCalabrese commented on dds/DCPS/security/SSL/DiffieHellman.cpp
> +
```suggestion
```

2022-03-03 18:34 UTC, iguessthislldo requested changes

2022-03-03 18:34 UTC, iguessthislldo commented on dds/DCPS/security/SSL/Certificate.cpp
> +  cache_dsign_algo_impl() : pkey_(NULL) {}
```suggestion
  cache_dsign_algo_impl() : pkey_(0) {}
```

2022-03-03 18:34 UTC, iguessthislldo commented on dds/DCPS/security/SSL/DiffieHellman.cpp
> +    if (!EVP_PKEY_get_utf8_string_param(keypair,"group", grp, glen, &glen)) {
```suggestion
    if (!EVP_PKEY_get_utf8_string_param(keypair, "group", grp, glen, &glen)) {
```

2022-03-03 18:34 UTC, iguessthislldo commented on dds/DCPS/security/SSL/DiffieHellman.cpp
> +      const unsigned char *pubbuf = 0;
```suggestion
      const char* gname = 0;
      const unsigned char* pubbuf = 0;
```

2022-03-03 18:34 UTC, iguessthislldo commented on dds/DCPS/security/SSL/DiffieHellman.cpp
> +  OSSL_PARAM *params;
```suggestion
  EVP_PKEY_CTX* ec_ctx;
  EVP_PKEY_CTX* fd_ctx;
  EVP_PKEY* peer;
  OSSL_PARAM_BLD* param_bld;
  OSSL_PARAM* params;
```

2022-03-03 19:20 UTC, iguessthislldo commented
Can you update this line to say that version 3 is also supported? https://github.com/objectcomputing/OpenDDS/blame/master/docs/dependencies.md#L187

2022-03-03 23:31 UTC, ClaytonCalabrese requested changes

2022-03-03 23:31 UTC, ClaytonCalabrese commented on dds/DCPS/security/SSL/DiffieHellman.cpp
> +          grp = (char *)p->data;
```suggestion
          grp = (char*)p->data;
```

2022-03-04 20:43 UTC, iguessthislldo approved these changes

2022-03-04 21:09 UTC, ClaytonCalabrese approved these changes

2022-03-05 15:50 UTC, mitza-oci commented on docs/dependencies.md
> +encryption and decryption. Versions 1.0, 1.1 and 3.0 are supported.
```suggestion
encryption and decryption. Versions 1.0, 1.1 and 3.0 (3.0.1 or later) are supported.
```

2022-03-05 15:50 UTC, merged