Fix Potential WaitSet Concurrent Wait Issues, Add Unit Test
objectcomputing/OpenDDS pull request #3417
Opened 2022-03-22 15:23 UTC by simpsont-oci

Problem: WaitSet was using two distinct approaches to atomic operations, which allowed for a potential race condition when multiple threads tried to call WaitSet::wait() on the same WaitSet object (which is intended to be prohibited by the spec).

Solution: Remove use of std::atomic / ACE_Atomic_Op and place `waiting_` under the protection of the object's mutex. In addition, add a real unit test for WaitSet and include testing of the new functionality as part of the unit test.

2022-03-22 18:30 UTC, iguessthislldo requested changes

2022-03-22 18:30 UTC, iguessthislldo commented on dds/DCPS/WaitSet.cpp
> +  if (waiting_ != false) {
```suggestion
  if (waiting_) {
```

2022-03-22 19:20 UTC, ClaytonCalabrese commented on tests/unit-tests/dds/DCPS/WaitSet.cpp
> +  std::thread thread([&](){
Is std::thread going to cause issues on certain builds?

2022-03-22 19:23 UTC, ClaytonCalabrese commented on tests/unit-tests/dds/DCPS/WaitSet.cpp
> +  std::thread thread([&](){
Never mind, I'm dumb and you already blocked properly for CPP11.

2022-03-23 04:30 UTC, sonndinh approved these changes

2022-03-23 16:33 UTC, iguessthislldo approved these changes

2022-03-23 19:03 UTC, merged