Spdp::fini_bit waits
objectcomputing/OpenDDS pull request #3445
Opened 2022-03-31 20:31 UTC by jrw972

Problem
-------

Waiting on a ReactorInterceptor::Command can cause deadlock (see

Solution
--------

Factor our a new class called BitSubscriber with atomic methods.

2022-04-22 17:48 UTC, mitza-oci requested changes

2022-04-22 17:48 UTC, mitza-oci commented on dds/DCPS/BuiltInTopicUtils.h
> +  BitSubscriber(const DDS::Subscriber_var& bit_subscriber)
```suggestion
  explicit BitSubscriber(const DDS::Subscriber_var& bit_subscriber)
```

2022-04-22 17:48 UTC, mitza-oci commented on dds/DCPS/BuiltInTopicUtils.h
> +  void bit_pub_listener_hack(DomainParticipantImpl* participant);
add comments addressing why it's a hack

2022-04-22 17:48 UTC, mitza-oci commented on dds/DCPS/BuiltInTopicUtils.cpp
> +  if (!CORBA::is_nil(bit_pub_dr.in())) {
```suggestion
  if (bit_pub_dr) {
```

2022-04-22 17:48 UTC, mitza-oci commented on dds/DCPS/BuiltInTopicUtils.cpp
> +    if (CORBA::is_nil(listener.in())) {
```suggestion
    if (listener) {
```

2022-04-22 17:48 UTC, mitza-oci commented on dds/DCPS/BuiltInTopicUtils.cpp
> +      TheServiceParticipant->job_queue()->enqueue(make_rch<DataReaderImpl::OnDataAvailable>(rchandle_from(sub), bit_pub_listener, rchandle_from(reader), true, false, false));
Does the `OnDataAvailable` constructor need both the reader and the subscriber?  Each reader already knows which subscriber it belongs to.

2022-04-27 03:10 UTC, iguessthislldo requested changes

2022-04-27 03:10 UTC, iguessthislldo commented on dds/DCPS/LinuxNetworkConfigMonitor.h
> +	return;
```suggestion
	    return;
```

2022-04-27 03:10 UTC, iguessthislldo commented on dds/DCPS/LinuxNetworkConfigMonitor.h
> +	return;
```suggestion
	    return;
```

2022-04-27 15:11 UTC, mitza-oci requested changes

2022-04-27 19:03 UTC, jrw972 commented on dds/DCPS/RTPS/Sedp.h
> +struct DiscoveredPublication : DCPS::PoolAllocationBase {
I'm wondering why this changed in the first place.

2022-04-29 13:26 UTC, mitza-oci approved these changes

2022-04-29 19:12 UTC, iguessthislldo approved these changes

2022-06-28 19:55 UTC, merged