RtpsRelay doesn't have embedded webserver for meta discovery
objectcomputing/OpenDDS pull request #3655
Opened 2022-08-02 21:58 UTC by jrw972

Problem
-------

Clients of an RtpsRelay must be configured with the SPDP, SEDP, and
DATA ports of an RtpsRelay instance.  This can be done statically or
dynamically.  In the dynamic scenario, it is convenient to use
TCP/HTTP load balancing to select an instance.  The instance can
return its ports in response to an HTTP request from the client.  For
load balancing, it is useful to include a health check endpoint that
is tied to the RtpsRelay admission control.

The HTTP server to provide this functionality can be implemented
external to the RtpsRelay.  However, deployments will be simplified by
including an embedded webserver in the RtpsRelay can serve the
configuration and answer the healthcheck.

Solution
--------

Embed a webserver in the RtpsRelay that can respond to configuration
and healthcheck requests.

2022-08-03 20:19 UTC, mitza-oci requested changes

2022-08-03 20:19 UTC, mitza-oci commented on tools/rtpsrelay/RelayHttpMetaDiscovery.cpp
> +  }
```suggestion
  respondStatus(response, proxy.admitting() ? HTTP_OK : HTTP_SERVICE_UNAVAILABLE);
```

2022-08-03 20:19 UTC, mitza-oci commented on tools/rtpsrelay/RelayHttpMetaDiscovery.cpp
> +      respond(response);
Why not use `relay.json` or something similar to name the resource?  It seems like that could better support extensibility.

2022-08-03 20:19 UTC, mitza-oci commented on tests/DCPS/RtpsRelay/Smoke/metachecker.cpp
> +    const char expected_response[]=
```suggestion
    const char expected_response[] =
```

2022-08-03 20:19 UTC, mitza-oci commented on tests/DCPS/RtpsRelay/Smoke/metachecker.cpp
> +  ACE_INET_Addr remote("127.0.0.1:8081");
configurable port?

2022-08-03 20:46 UTC, jrw972 commented on tools/rtpsrelay/RtpsRelay.cpp
> +  const unsigned short DEFAULT_META = 8080;
That sounds like a good reason to use 8080.

2022-08-03 21:21 UTC, mitza-oci approved these changes

2022-08-04 04:25 UTC, iguessthislldo approved these changes

2022-08-04 13:22 UTC, merged