DataWriter doesn't remove unregistered instances
objectcomputing/OpenDDS pull request #3684
Opened 2022-08-16 20:07 UTC by jrw972

Problem
-------

Entries in the maps of DataWriterImpl_t and WriteDataContainer
correspond to instances.  Unregistering an instance should remove from
these maps to prevent a memory leak.

Solution
--------

Remove from these maps when instances are unregistered.

2022-08-16 21:36 UTC, mitza-oci requested changes

2022-08-16 21:36 UTC, mitza-oci commented on dds/DCPS/DataWriterImpl_T.h
> +      // TODO: Will this comparison work correctly?
TODO

2022-08-16 21:38 UTC, mitza-oci approved these changes

2022-08-16 22:03 UTC, iguessthislldo requested changes

2022-08-16 22:03 UTC, iguessthislldo commented on dds/DCPS/WriteDataContainer.cpp
> +    ACE_UNUSED_ARG(registered_sample);
I don't think this line is needed since this variable is always used.

2022-08-17 07:51 UTC, jwillemsen commented
Any explicit unit test possible for this?

2022-08-17 13:44 UTC, jrw972 commented
> Any explicit unit test possible for this?

Possible yes.  However, I think it's going to take a serious refactoring of DataWriterImpl_T, DataWriterImpl, WriteDataContainer, and the associated transport framework to write it as a unit test and not an integration test.

2022-08-17 16:50 UTC, iguessthislldo approved these changes

2022-08-17 16:54 UTC, mitza-oci commented
> Any explicit unit test possible for this?

FooTest3_0 is not exactly a unit test, but it will provide coverage of these code paths

2022-08-18 19:08 UTC, merged