Add `AtomicBool` Class
objectcomputing/OpenDDS pull request #3754
Opened 2022-09-27 07:54 UTC by iguessthislldo

2022-09-29 14:26 UTC, jrw972 requested changes

2022-09-29 14:26 UTC, jrw972 commented on dds/DCPS/ReplayerImpl.cpp
> +  // if (this->publisher_servant_->is_enabled()) {
```suggestion
  // if (!this->publisher_servant_->is_enabled()) {
```

2022-09-29 15:06 UTC, simpsont-oci requested changes
Please add a unit test for AtomicBool (multithreaded would be ideal (see ServiceEventDispatcher unit test for example of relatively easy multithreading)). A simple unit test for SafeBool_T would be nice as well, that way they'll both be sure to get tsan & ubsan coverage.

2022-10-05 00:33 UTC, iguessthislldo commented
> Please add a unit test for AtomicBool (multithreaded would be ideal (see ServiceEventDispatcher unit test for example of relatively easy multithreading)).

I think what I added for AtomicBool should be sufficient for tsan since I think it just has to be accessing the memory for it to check it and I don't actually have to assert the value.

2022-10-05 01:03 UTC, simpsont-oci approved these changes

2022-10-06 13:44 UTC, jrw972 approved these changes

2022-10-07 20:14 UTC, merged