Building for VxWorks on Windows
objectcomputing/OpenDDS pull request #3755
Opened 2022-09-28 14:10 UTC by ocielliottc

- Modified opendds_idl and tao_idl cmake files to build for VxWorks on Windows.
- Split library dependencies based on OPENDDS_XERCES3 and OPENDDS_SECURITY.

2022-09-28 20:39 UTC, iguessthislldo approved these changes

2022-09-28 20:41 UTC, iguessthislldo requested changes
CMake tests appear to be broken

2022-10-07 16:28 UTC, ocielliottc commented
@iguessthislldo @mitza-oci It appears that I have moved past the cmake errors.  I could be wrong, but the run-time errors don't look like a result of my changes.  Could you please verify?  Thanks.

2022-10-07 18:22 UTC, iguessthislldo approved these changes
Yes. I think it looks alright now.

2022-10-07 20:14 UTC, merged