Reduce RtpsUdpReceiveStrategy Warning to Info
objectcomputing/OpenDDS pull request #3863
Opened 2022-11-08 19:17 UTC by simpsont-oci

Problem: This pathway is common and expected and not indicative of an error condition, so it shouldn't be a warning message.
Solution: Downgrade to "info".:

2022-11-08 19:36 UTC, mitza-oci approved these changes

2022-11-08 20:14 UTC, iguessthislldo requested changes

2022-11-08 20:14 UTC, iguessthislldo commented on dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp
> +      ACE_DEBUG((LM_INFO, "(%P|%t) RtpsUdpReceiveStrategy::handle_input: reallocating primary receive buffer based on reference count\n"));
[A recent-ish change to the guidelines](https://github.com/objectcomputing/OpenDDS/pull/3773/files#diff-c41bbceadcfb43d46a0cd4c55579e0b16ca68b85f7dc11dcafad9a3e94adc399)

```suggestion
      ACE_DEBUG((LM_INFO, "(%P|%t) INFO: RtpsUdpReceiveStrategy::handle_input: reallocating primary receive buffer based on reference count\n"));
```

2022-11-09 19:42 UTC, iguessthislldo approved these changes

2022-11-10 04:11 UTC, merged