Test Where TypeSupport is Used as a Plugin
objectcomputing/OpenDDS pull request #3871
Opened 2022-11-11 06:26 UTC by iguessthislldo

2022-11-11 06:57 UTC, jwillemsen commented on tests/DCPS/TypeSupportPlugin/TypeSupportPlugin.cpp
> +  printf("Getting TypeSupport for %s\n", type_name);
Why not use ACE_DEBUG?

2022-11-11 15:50 UTC, mitza-oci requested changes

2022-11-11 15:50 UTC, mitza-oci commented on tests/DCPS/TypeSupportPlugin/TypeSupportPlugin.cpp
> +  printf("Name according to type support is %s\n", ts_name.in());
Should the test fail if the name wasn't expected?
Any other verification steps like using the TypeSupport to get the DynamicType?

2022-11-11 15:50 UTC, mitza-oci commented on tests/DCPS/TypeSupportPlugin/run_test.pl
> +eval '(exit $?0)' && eval 'exec perl -S $0 ${1+"$@"}'
Can this be added to a test .lst file?

2022-11-17 18:53 UTC, mitza-oci approved these changes

2022-11-17 20:10 UTC, mitza-oci requested changes

2022-11-17 20:10 UTC, mitza-oci commented on tests/DCPS/TypeSupportPlugin/TypeSupportPlugin.mpc
> +}
```suggestion
  IDL_Files {
  }
}
```
Defaults to `*.idl` which doesn't seem to be what we want here

2022-11-18 14:43 UTC, mitza-oci approved these changes
Ready to merge once this CI error is fixed https://github.com/objectcomputing/OpenDDS/actions/runs/3496083930/jobs/5854701992#step:16:17

2022-11-19 21:10 UTC, merged