Fix Coverity
objectcomputing/OpenDDS pull request #3907
Opened 2022-12-01 20:19 UTC by jrw972

2022-12-01 20:22 UTC, iguessthislldo approved these changes

2022-12-01 21:56 UTC, simpsont-oci commented on dds/InfoRepo/DCPSInfoRepoServ.cpp
> +  } catch(const OpenDDS::Federator::Incomplete&) {}
```suggestion
  } catch (const OpenDDS::Federator::Incomplete&) {}
```

2022-12-01 22:08 UTC, simpsont-oci approved these changes

2022-12-01 22:38 UTC, sonndinh requested changes

2022-12-01 22:38 UTC, sonndinh commented on dds/DCPS/XTypes/DynamicDataImpl.cpp
> +  : kind_(TK_STRING8), active_(&str_), str_(ACE_OS::strdup(str))
```suggestion
  : kind_(TK_STRING8), active_(0), str_(ACE_OS::strdup(str))
```
`active_` pointer isn't used for this member.

2022-12-01 22:38 UTC, sonndinh commented on dds/DCPS/XTypes/DynamicDataImpl.cpp
> +  : kind_(TK_STRING16), active_(&wstr_), wstr_(ACE_OS::strdup(wstr))
```suggestion
  : kind_(TK_STRING16), active_(0), wstr_(ACE_OS::strdup(wstr))
```
Similar to the narrow string case.

2022-12-02 15:09 UTC, sonndinh approved these changes

2022-12-02 21:30 UTC, merged