Conditionally include OpenDDSConfig.h, fixes #4497
objectcomputing/OpenDDS pull request #4498
Opened 2024-02-29 08:19 UTC by jwillemsen

* dds/DCPS/Definitions.h:

2024-02-29 18:32 UTC, iguessthislldo commented
We can't change it back to that because it requires C++17 and we don't want to require that just to use #4492. You can read more about the config file design [here](https://github.com/OpenDDS/OpenDDS/wiki/Proposal:-Header-file-for-compile%E2%80%90time-configuration). We did discuss an alternative where a macro could be used to ignore the config file. Something like:

```C++
#ifndef OPENDDS_IGNORE_CONFIG_FILE
#  include <dds/OpenDDSConfig.h>
#endif
```

2024-02-29 18:43 UTC, jwillemsen commented
A macro will also work, I can add that to the ace/config.h file. for ACE7 I want to move to c++17 this year, so we could like this pr to that upgrade

2024-03-01 20:00 UTC, iguessthislldo requested changes
This looks okay to us. The only change I think is needed is to add it to the [news file](https://github.com/OpenDDS/OpenDDS/blob/aee0af4556a4e92d1ac73c7fc063948a7cff2100/docs/news.d/openddsconfig.rst?plain=1#L1). Please add this PR number to the top (`.. news-prs: 4482 4497`) and this as an alternative in the manual configuration line.

2024-03-04 18:08 UTC, iguessthislldo requested changes

2024-03-04 18:08 UTC, iguessthislldo commented on docs/news.d/openddsconfig.rst
> +    add the define `OPENDDS_IGNORE_OPENDDSCONFIG_H_FILE` to their `ace/config.h` file
```suggestion
    add the define ``OPENDDS_IGNORE_OPENDDSCONFIG_H_FILE`` to their ``ace/config.h`` file.
```

2024-03-04 19:02 UTC, iguessthislldo approved these changes

2024-03-04 19:02 UTC, merged